bustype: virtual

emulate_nodes: yes

# enable specific node emulation
emulate_tsi: yes
emulate_packs: yes
emulate_cockpit: no
emulate_motorcontroller: no

# CAN node ids
can_nodes:
  3: tsi
  1: pack1
  2: pack2


# structure of data in PDOs

# NOTE: PDO length cannot exceed 8 bytes, if a 
#       list has less than 8 elements, the remaining
#       bytes will be ignored

tsi_pdo:
  - COOLING_TEMP_1
  - COOLING_TEMP_2
  - FLOWRATE
  - STATE
  - TS_CURRENT
  - TS_VOLTAGE

ams_pdo:
  - Cell1Temp
  - ambient_temp
  - state_of_charge1
  - state_of_charge2
  - voltage


# NOTE: make sure that there is a calibration function
#       defined for every item listed here

data_processor_pdo:
  - TS_POWER           # Sum of each pack voltage
  # - PackTemp_Farenheit  # pack1 temperature in farenheit
  # - tsi - flowrate


# Other data to keep track of
# need to poll this data manually
sdo_data:

  Cell1Temp:
    node_id: 2
    index: 2011
    poll_rate: 10

  MotorTemp:
    node_id: 1
    index: 2010
    subindex: 0
    poll_rate: 0.5


# modules
logger:
  enable: yes
  database_path: /home/fsae/log.db
  wipe_database_on_reset: yes

data_processor:
  enable: yes

calibration:
  - tsi-cal.py    # all of the tsi sensors need client-side calibration
  - user-cal.py   # for custom properties

gui:
  enable: no

web_server:
  enable: no

# All sensors that will report to SCADA, divided into top-level groups
sensors:
  GLV:
    - Voltage
    - Current
    - Power
    - Temp
  TSI:
    - High Voltage
    - HV Current
  Cooling:
    - Temp1
    - Temp2
    - Flow Rate
    - Pump
    - Fan
  Motor Controller:
    - Voltage
    - Motor Temp
    - RPM
    - Velocity
  Pack 1:
    - Voltage
    - Current
    - Ambient Temp
    - Charge Current
  Pack 2:
    - Voltage
    - Current
    - Ambient Temp
    - Charge Current

# List of car drive states that are in the state FSM
drive_states:
  - GLV Off
  - GLV On
  - Precharge
  - TS Energized
  - Ready to Drive
  - AMS Fault
  - IMD Fault
  - Brake Overtravel

# All nodes on the safety loop that are measurable and reportable to SCADA
sloop_nodes:
  - TSI, S1
  - TSI, S2
  - Pack 1, S1
  - Pack 1, S2
  - Pack 2, S1
  - Pack 2, S2

# All digital systems that can open the safety loop
sloop_systems:
  - TSI
  - Pack 1
  - Pack 2
  - SCADA