bustype: virtual

emulate_nodes: yes

# enable specific node emulation
emulate_tsi: yes
emulate_packs: yes
emulate_cockpit: no
emulate_motorcontroller: no

# CAN node ids
can_ids:
  tsi: 3
  pack1: 2


# structure of data in PDOs
tsi_pdo:
  - coolingtemp1
  - coolingtemp2
  - flowrate
  - state
  - throttle
  - unused
  - unused
  - unused

ams_pdo:
  - Cell1Temp
  - ambient_temp
  - state_of_charge1
  - state_of_charge2
  - unused
  - unused
  - unused
  - unused

data_processor_pdo1:
  - average_current         # TS current averaged over 10 seconds
  - net_state_of_charge     # Sum of State of Charge of both packs
  - estimated_car_velocity  # Motor Velocity * Gear Ratio * Wheel Circumference
  - PackTemp_Farenheit      # What country are we in?
  - unused
  - unused  # etc.
  - unused
  - unused


# Other data to keep track of
# need to poll this data manually
sdo_data:

  Cell1Temp:
    node_id: 2
    index: 2011
    poll_rate: 10

  MotorTemp:
    node_id: 1
    index: 2010
    subindex: 0
    poll_rate: 0.5


# modules
logger:
  enable: yes
  database_path: /home/fsae/log.db
  wipe_database_on_reset: yes

data_processor:
  enable: yes

gui:
  enable: no

web_server:
  enable: no

sensors:
  GLV:
    - Voltage
    - Current
    - Power
    - Temp
  TSI:
    - High Voltage
    - HV Current
  Cooling:
    - Temp1
    - Temp2
    - Flow Rate
    - Pump
    - Fan
  Motor Controller:
    - Voltage
    - Motor Temp
    - RPM
    - Velocity
  Pack 1:
    - Voltage
    - Current
    - Ambient Temp
    - Charge Current
  Pack 2:
    - Voltage
    - Current
    - Ambient Temp
    - Charge Current

drive_states:
  - GLV Off
  - GLV On
  - Precharge
  - TS Energized
  - Ready to Drive
  - AMS Fault
  - IMD Fault
  - Brake Overtravel

sloop_nodes:
  - TSI, S1
  - TSI, S2
  - Pack 1, S1
  - Pack 1, S2
  - Pack 2, S1
  - Pack 2, S2
  - SCADA