bus_info:
  bustype: virtual
  channel: vcan0
  bitrate: 125000

emulate_nodes: yes

# enable specific node emulation
emulate_tsi: yes
emulate_packs: yes
emulate_cockpit: no
emulate_motorcontroller: no

# CAN node ids
can_nodes:
  3: TSI
  1: PACK1
  2: PACK2


# structure of data in PDOs

# NOTE: PDO length cannot exceed 8 bytes, if a 
#       list has less than 8 elements, the remaining
#       bytes will be ignored

process_data:
  TSI:    [ COOLING_TEMP_1, COOLING_TEMP_2, FLOWRATE, STATE, TS_CURRENT, TS_VOLTAGE ]
  PACK1:  [ VOLTAGE, CURRENT, SOC_1, SOC_2, AMBIENT_TEMP, 'MIN_CELL_TEMP', AVG_CELL_TEMP, MAX_CELL_TEMP ]
  PACK2:  [ VOLTAGE, CURRENT, SOC_1, SOC_2, AMBIENT_TEMP, MIN_CELL_TEMP, AVG_CELL_TEMP, MAX_CELL_TEMP ]
  SCADA:  [ TS_POWER ]


# Other data to keep track of
# need to poll this data manually
service_data:

  Cell1Temp:
    node_id: 2
    index: 2011
    poll_rate: 10

  MotorTemp:
    node_id: 1
    index: 2010
    subindex: 0
    poll_rate: 0.5


# modules
logger:
  enable: yes
  database_path: /home/fsae/log.db
  wipe_database_on_reset: yes

data_processor:
  enable: yes


# \/                             \/
# \/  GUI Configuration Options  \/
# \/                             \/

# NOTE: if sensor is string, it is ignored during update loop
#       if sensor is a list treat first value as the label,
#       second value as the data key, and third value as the unit
#
#       Format for oprange (sensor operating range):
#           [lower_error, lower_warning, upper_warning, upper_error]

GUI:
  Sensors: # All sensors that will report to SCADA, divided into top-level groups
    GLV:
      Voltage:
        data_target: Null
        unit: 'V'
        oprange: [10, 15, 65, 70]
        open_sloop_out_of_range: no
      Current:
        data_target: Null
        unit: 'A'
        oprange: [10, 15, 65, 70]
        open_sloop_out_of_range: no
      Power:
        data_target: Null
        unit: 'kW'
        oprange: Null
        open_sloop_out_of_range: no
      Temp:
        data_target: Null
        unit: 'C'
        oprange: [10, 15, 65, 70]
        open_sloop_out_of_range: no
    
    TSI:
      TS Voltage:
        data_target: 'TSI: TS_VOLTAGE'
        unit: 'V'
        oprange: [80, 90, 120, 150]
        open_sloop_out_of_range: no
      TS Current:
        data_target: 'TSI: TS_CURRENT'
        unit: 'A'
        oprange: [Null, Null, 250, 300]
        open_sloop_out_of_range: yes
      TS Power:
        data_target: 'SCADA: TS_POWER'
        unit: 'kW'
        oprange: [10, 15, 65, 70]
        open_sloop_out_of_range: no
    
    Cooling:
      Temp1:
        data_target: Null
        unit: ''
        oprange: []
        open_sloop_out_of_range: no
      Temp2:
        data_target: Null
        unit: ''
        oprange: []
        open_sloop_out_of_range: no
      Flow Rate:
        data_target: Null
        unit: ''
        oprange: []
        open_sloop_out_of_range: no
      Pump:
        data_target: Null
        unit: ''
        oprange: []
        open_sloop_out_of_range: no
      Fan:
        data_target: Null
        unit: ''
        oprange: []
        open_sloop_out_of_range: no
    
    Motor Controller:
      Voltage:
        data_target: Null
        unit: ''
        oprange: []
        open_sloop_out_of_range: no
      Motor Temp:
        data_target: Null
        unit: ''
        oprange: []
        open_sloop_out_of_range: no
      RPM:
        data_target: Null
        unit: ''
        oprange: []
        open_sloop_out_of_range: no
      Velocity:
        data_target: Null
        unit: ''
        oprange: []
        open_sloop_out_of_range: no
    
    Pack 1:
      SOC:
        data_target: 'PACK1: SOC_1'
        unit: '%'
        oprange: [10, 20, 100, 105]
        open_sloop_out_of_range: no
      Voltage:
        data_target: 'PACK1: VOLTAGE'
        unit: 'V'
        oprange: [Null, Null, 250, 300]
        open_sloop_out_of_range: no
      Current:
        data_target: 'PACK1: CURRENT'
        unit: 'A'
        oprange: [Null, Null, 250, 300]
        open_sloop_out_of_range: no
      Ambient Temp:
        data_target: 'PACK1: AMBIENT_TEMP'
        unit: 'C'
        oprange: [Null, Null, 250, 300]
        open_sloop_out_of_range: no
    
    Pack 2:
      SOC:
        data_target: 'PACK2: SOC_1'
        unit: '%'
        oprange: [10, 20, 100, 105]
        open_sloop_out_of_range: no
      Voltage:
        data_target: 'PACK2: VOLTAGE'
        unit: 'V'
        oprange: [Null, Null, 250, 300]
        open_sloop_out_of_range: no
      Current:
        data_target: 'PACK2: CURRENT'
        unit: 'A'
        oprange: [Null, Null, 250, 300]
        open_sloop_out_of_range: no
      Ambient Temp:
        data_target: 'PACK2: AMBIENT_TEMP'
        unit: 'C'
        oprange: [Null, Null, 250, 300]
        open_sloop_out_of_range: no
  
  Drive States: # List of car drive states that are in the state FSM
    - GLV Off
    - GLV On
    - Precharge
    - TS Energized
    - Ready to Drive
    - AMS Fault
    - IMD Fault
    - Brake Overtravel
  Safety Loop Systems: # All digital systems that can open the safety loop
    - TSI
    - Pack 1
    - Pack 2
    - SCADA
  Safety Loop Nodes: # All nodes on the safety loop that are measurable and reportable to SCADA
    - TSI, S1
    - TSI, S2
    - Pack 1, S1
    - Pack 1, S2
    - Pack 2, S1
    - Pack 2, S2