bus_info:
  bustype: virtual
  channel: vcan0
  bitrate: 125000

emulate_nodes: yes

# enable specific node emulation
emulate_tsi: yes
emulate_packs: yes
emulate_cockpit: no
emulate_motorcontroller: no

# CAN node ids
can_nodes:
  3: TSI
  1: PACK1
  2: PACK2


# structure of data in PDOs

# NOTE: PDO length cannot exceed 8 bytes, if a 
#       list has less than 8 elements, the remaining
#       bytes will be ignored

process_data:
  TSI:    [ COOLING_TEMP_1, COOLING_TEMP_2, FLOWRATE, STATE, TS_CURRENT, TS_VOLTAGE ]
  PACK1:  [ VOLTAGE, SOC_1, SOC_2, AMBIENT_TEMP, CELL_01_TEMP ]
  PACK2:  [ VOLTAGE, SOC_1, SOC_2, AMBIENT_TEMP, CELL_01_TEMP ]
  SCADA:  [ TS_POWER ]


# Other data to keep track of
# need to poll this data manually
service_data:

  Cell1Temp:
    node_id: 2
    index: 2011
    poll_rate: 10

  MotorTemp:
    node_id: 1
    index: 2010
    subindex: 0
    poll_rate: 0.5


# modules
logger:
  enable: yes
  database_path: /home/fsae/log.db
  wipe_database_on_reset: yes

data_processor:
  enable: yes


# \/                             \/
# \/  GUI Configuration Options  \/
# \/                             \/

# NOTE: if sensor is string, it is ignored during update loop
#       if sensor is a list treat first value as the label,
#       second value as the data key, and third value as the unit

GUI:
  Sensors: # All sensors that will report to SCADA, divided into top-level groups
    GLV:
      - Voltage
      - Current
      - Power
      - Temp
    TSI:
      - [ TS Voltage, 'TSI: TS_VOLTAGE', V ]
      - [ TS Current, 'TSI: TS_CURRENT', A ]
      - [ TS Power, 'SCADA: TS_POWER', kW ]
    Cooling:
      - Temp1
      - Temp2
      - Flow Rate
      - Pump
      - Fan
    Motor Controller:
      - Voltage
      - Motor Temp
      - RPM
      - Velocity
    Pack 1:
      - SOC
      - Voltage
      - Current
      - [ Ambient Temp, 'PACK1: AMBIENT_TEMP', C ]
      - Charge Current
    Pack 2:
      - SOC
      - Voltage
      - Current
      - Ambient Temp
      - Charge Current
  Drive States: # List of car drive states that are in the state FSM
    - GLV Off
    - GLV On
    - Precharge
    - TS Energized
    - Ready to Drive
    - AMS Fault
    - IMD Fault
    - Brake Overtravel
  Safety Loop Systems: # All digital systems that can open the safety loop
    - TSI
    - Pack 1
    - Pack 2
    - SCADA
  Safety Loop Nodes: # All nodes on the safety loop that are measurable and reportable to SCADA
    - TSI, S1
    - TSI, S2
    - Pack 1, S1
    - Pack 1, S2
    - Pack 2, S1
    - Pack 2, S2