GUI:
  Sensors:
    GLV:
      Voltage:
          data_target: 'GLV: VOLTAGE'
          unit: 'V'
          oprange: [10, 15, 65, 70]
          open_sloop_out_of_range: no
      Current:
          data_target: 'GLV: CURRENT'
          unit: 'A'
          oprange: [10, 15, 65, 70]
          open_sloop_out_of_range: no
      Power:
          data_target: 'GLV: POWER'
          unit: 'kW'
          oprange: [10, 15, 65, 70]
          open_sloop_out_of_range: no
      Temp:
          data_target: 'GLV: TEMP'
          unit: 'C'
          oprange: [10, 15, 65, 70]
          open_sloop_out_of_range: no
    TSI:
      TS Voltage:
          data_target: 'TSI: TS_VOLTAGE'
          unit: 'V'
          oprange: [10, 15, 65, 70]
          open_sloop_out_of_range: no
      TS Current:
          data_target: 'TSI: TS_CURRENT'
          unit: 'A'
          oprange: [Null, Null, 250, 300]
          open_sloop_out_of_range: yes
      TS Power:
          data_target: 'SCADA: TS_POWER'
          unit: 'kW'
          oprange: [10, 15, 65, 70]
          open_sloop_out_of_range: no